# Generated by Django 4.0.3 on 2023-09-07 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='date',
        ),
    ]
