# Generated by Django 4.0.3 on 2023-09-11 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_appointment_vin_appointment_vip_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='vip_status',
            new_name='vip',
        ),
    ]
